# Generated by Django 5.1.1 on 2024-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='menyu',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
